### ISSUE TITLE
Power Profiler current measurements showing 0 on 100ms scale.

### ISSUE THREAD

**Issue by markb-EE** [NordicSemiconductor/pc-nrfconnect-ppk#374]
If the Power Profiler app, when the 100 ms scale is selected, the average, max and charge boxes all read 0.

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/assets/8332189/0ef089b4-12a6-4bbf-985d-8710ee9a726e)

**Comment by datenreisender** [comment]
I was unable to reproduce this. If this was also done with 4.0.0-beta1: Could you first check whether this problem still exists with the latest version? Does it only happen at 100ms, not above or below? Could you export a run to a .ppk file and share it?

**Comment by KonstKonovalov** [comment]
Average calculation is still incorrect in version v.4.0.0-beta3. The average current cannot be greater than the max current.
<img width="1001" alt="image" src="https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/assets/22951635/6f40c9e2-bbe6-4cf8-82d1-b5165b9be054">
[ppk-20231229T142044.zip](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/files/13794204/ppk-20231229T142044.zip)

**Comment by datenreisender** [comment]
Ah, yes, I am now able to reproduce this with your PPK file by navigating to one of the peaks and then zooming in. Seems the further I zoom in, the further the values are off. 

Also interesting that in your image the location in the minimap is wrong, since it shows you to be left of the peak.

Thanks for the PPK file!

@kylebonnici: Do you have an idea what causes this? 

<img width="1133" alt="image" src="https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/assets/260705/3210e72c-a53f-4a46-929d-f700df2e8cf5">

**Comment by kylebonnici** [comment]
Issue has been found and a PR will follow soon the issue is that the average is off by a factor of 1000 as we have change the unit in the chart and omit changing unit in the Window average box

![Capture](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/assets/10996496/ce85f7d8-a930-4985-9b87-b0273c852b5a)

**Comment by kylebonnici** [comment]
Will look at the other issue where values are zeros

**Comment by kylebonnici** [comment]
Hi @markb-EE and @KonstKonovalov version 4.0.0-beta4 is out and should address these issues
